### PR TITLE
Source distributions

### PR DESCRIPTION
**Pull request by miki5799**
I'd like to bump support for hosted distribution archives in case a specific environment (e.g. Mac M1 python3.10) needs pip to build it's own wheel.

### CODE REVIEW

**Comment by ringsaturn** [comment]
It’s a bug for missing macOS Python 3.10 wheels and shall be fixed in the next release. https://github.com/ringsaturn/tzfpy/compare/v0.15.3...main


Wheels and tar.gz should not be included in repo but built in GitHub Actions instead.

**Comment by ringsaturn** [comment]
I may release a new version within a week and will close this PR after that.

**Comment by miki5799** [comment]
> Wheels and tar.gz should not be included in repo but built in GitHub Actions instead.

That makes sense, thanks for clarifying!

**Comment by ringsaturn** [comment]
@miki5799 I have released v0.15.4 and you can install Python 3.10 M1 Mac wheel from PyPI.

https://pypi.org/project/tzfpy/0.15.4/#files

**Comment by miki5799** [comment]
Thank you very much! Installation was successful.

**Comment by miki5799** [comment]
@ringsaturn Could you host an Apple Silicon wheel for `v0.15.3`, since a dependency needs that specific version? Thanks in advance

**Comment by ringsaturn** [comment]
> @ringsaturn Could you host an Apple Silicon wheel for `v0.15.3`, since a dependency needs that specific version? Thanks in advance

Sorry to tell you that I don't have to do this and wheel files are built in GitHub Actions not from my local computer. I suggest you bump you tzfpy version to fix this since there are not breaking changes between `v0.15.3` to current latest `v0.15.5`.

Or, you can try install it via [tzfpy's conda distribution](https://anaconda.org/conda-forge/tzfpy), because in conda tzfpy use different build steps so [macOS Arm wheels are not missing in `v0.15.3`](https://anaconda.org/conda-forge/tzfpy/files?version=0.15.3&type=conda)

**Pull request closed without merging**
